[package]
name = "neuras"
version = "0.1.0"
authors = ["Joaquín R <globojorro@gmail.com>"]

[dependencies]
error-chain = "~0.11.0-rc.2"
url = "1.5.1"
zmq = { git = "https://github.com/erickt/rust-zmq.git" }

[profile.release]
lto = true
