[package]
name = "neuras"
version = "0.1.1"
authors = ["Joaquín R <globojorro@gmail.com>"]

[dependencies]
error-chain = "~0.11.0-rc.2"
futures = "0.1.14"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
url = "1.5.1"
zmq = { git = "https://github.com/erickt/rust-zmq.git" }
zmq-tokio = { git = "https://github.com/saibatizoku/zmq-tokio.git" }

[profile.release]
lto = true
