[package]
name = "neuras"
version = "0.1.2"
authors = ["Joaquín R <globojorro@gmail.com>"]

[dependencies]
bitflags = "1.0"
chrono = "0.4"
error-chain = "0.11.0"
futures = "0.1.14"
serde = "1.0"
serde_derive = "1.0"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
tokio-signal = "0.1"
toml = "0.4"
uuid = { version = "0.5", features = ["serde", "v4", "v5"] }
url = "1.5.1"
zmq = { git = "https://github.com/erickt/rust-zmq.git" }
zmq-tokio = { git = "https://github.com/saibatizoku/zmq-tokio.git" }

[profile.release]
lto = true

[[example]]
name = "actorling"
path = "examples/actorling.rs"

[[example]]
name = "ciphered-sockets"
path = "examples/ciphered-sockets.rs"

[[example]]
name = "tokio-client"
path = "examples/tokio-client.rs"
